#!/usr/bin/env ruby
$LOAD_PATH.unshift('lib')

require 'options'
require 'book'
require 'chapter'
require 'notes_generator'

options = Options.new
options.parse!

exit unless options.continue?

if options.generate?
  require 'import_controller'
  ImportController.new(options.file).run
elsif options.create_new?
  require 'yaml_generator'
  YamlGenerator.new(options.file).run
end
